<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>false</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ForceDesignerDpiUnaware>false</ForceDesignerDpiUnaware>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="MainForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Downloader.Core\Downloader.Core.csproj" />
    <ProjectReference Include="..\Downloader.Network\Downloader.Network.csproj" />
    <ProjectReference Include="..\Downloader.Monitoring\Downloader.Monitoring.csproj" />
    <ProjectReference Include="..\Downloader.Threading\Downloader.Threading.csproj" />
  </ItemGroup>

</Project>
